apiVersion: v1
kind: Service
metadata:
  name: eventuate-local-cdc-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    svc: eventuate-local-cdc-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eventuate-local-cdc-service
  labels:
    application: ftgo
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        svc: eventuate-local-cdc-service
    spec:
      containers:
      - name: eventuate-local-cdc-service
        image: eventuateio/eventuateio-local-cdc-service:0.17.0.RELEASE
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: httpport
        command: ["bash", "-c", "java -Dsun.net.inetaddr.ttl=30 -jar *.jar" ]
        env:
          - name: JAVA_OPTS
            value: "-Dsun.net.inetaddr.ttl=30"
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://ftgo-mysql/eventuate
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: ftgo-db-secret
                key: username
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ftgo-db-secret
                key: password
          - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
            value: com.mysql.jdbc.Driver
          - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
            value: ftgo-kafka:9092
          - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
            value: ftgo-zookeeper:2181
          - name: EVENTUATELOCAL_CDC_DB_USER_NAME
            value: root
          - name: EVENTUATELOCAL_CDC_DB_PASSWORD
            value: rootpassword
          - name: EVENTUATELOCAL_CDC_LEADERSHIP_LOCK_PATH
            value: /eventuatelocal/cdc/leader1
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
---
